
/**
 * @fileoverview Categorizes host domains and processes raw browsing databases into structures suitable for Chart.js treemaps, heatmaps, and timelines.
 *
 * Imported by the Insights tab dashboard component to prepare visualization records.
 */

const CATEGORY_MAP = {

  // ══════════════════════════════════════════════════════════════════════════
  // DEVELOPMENT
  // ══════════════════════════════════════════════════════════════════════════
  "github.com":                    "Development",
  "stackoverflow.com":             "Development",
  "npmjs.com":                     "Development",
  "localhost":                     "Development",
  "gitlab.com":                    "Development",
  "bitbucket.org":                 "Development",
  "codepen.io":                    "Development",
  "jsfiddle.net":                  "Development",
  "replit.com":                    "Development",
  "codesandbox.io":                "Development",
  "leetcode.com":                  "Development",
  "hackerrank.com":                "Development",
  "codeforces.com":                "Development",
  "developer.mozilla.org":         "Development",
  "docs.python.org":               "Development",
  "docs.microsoft.com":            "Development",
  "learn.microsoft.com":           "Development",
  "developer.apple.com":           "Development",
  "developer.android.com":         "Development",
  "reactjs.org":                   "Development",
  "vuejs.org":                     "Development",
  "angular.io":                    "Development",
  "svelte.dev":                    "Development",
  "nextjs.org":                    "Development",
  "nuxt.com":                      "Development",
  "tailwindcss.com":               "Development",
  "getbootstrap.com":              "Development",
  "webpack.js.org":                "Development",
  "vite.dev":                      "Development",
  "babeljs.io":                    "Development",
  "eslint.org":                    "Development",
  "prettier.io":                   "Development",
  "typescriptlang.org":            "Development",
  "rust-lang.org":                 "Development",
  "golang.org":                    "Development",
  "kotlinlang.org":                "Development",
  "swift.org":                     "Development",
  "php.net":                       "Development",
  "ruby-lang.org":                 "Development",
  "rubygems.org":                  "Development",
  "pypi.org":                      "Development",
  "crates.io":                     "Development",
  "packagist.org":                 "Development",
  "hub.docker.com":                "Development",
  "kubernetes.io":                 "Development",
  "terraform.io":                  "Development",
  "ansible.com":                   "Development",
  "jenkins.io":                    "Development",
  "circleci.com":                  "Development",
  "travis-ci.com":                 "Development",
  "sonarqube.org":                 "Development",
  "postman.com":                   "Development",
  "swagger.io":                    "Development",
  "graphql.org":                   "Development",
  "mongodb.com":                   "Development",
  "postgresql.org":                "Development",
  "mysql.com":                     "Development",
  "redis.io":                      "Development",
  "elastic.co":                    "Development",
  "supabase.com":                  "Development",
  "prisma.io":                     "Development",
  "planetscale.com":               "Development",
  "vercel.com":                    "Development",
  "netlify.com":                   "Development",
  "heroku.com":                    "Development",
  "render.com":                    "Development",
  "railway.app":                   "Development",
  "fly.io":                        "Development",
  "digitalocean.com":              "Development",
  "linode.com":                    "Development",
  "vultr.com":                     "Development",
  "algolia.com":                   "Development",
  "sentry.io":                     "Development",
  "datadog.com":                   "Development",
  "newrelic.com":                  "Development",
  "grafana.com":                   "Development",
  "prometheus.io":                 "Development",
  "codeclimate.com":               "Development",
  "snyk.io":                       "Development",
  "w3schools.com":                 "Development",
  "css-tricks.com":                "Development",
  "smashingmagazine.com":          "Development",
  "dev.to":                        "Development",
  "hashnode.com":                  "Development",
  "freecodecamp.org":              "Development",
  "theodinproject.com":            "Development",
  "exercism.org":                  "Development",
  "codewars.com":                  "Development",
  "cloud.google.com":              "Development",
  "aws.amazon.com":                "Development",
  "azure.microsoft.com":           "Development",
  "console.aws.amazon.com":        "Development",
  "console.cloud.google.com":      "Development",
  "portal.azure.com":              "Development",
  "ibm.com/cloud":                 "Development",
  "oracle.com/cloud":              "Development",
  "cloudflare.com":                "Development",
  "fastly.com":                    "Development",
  "akamai.com":                    "Development",
  "nginx.com":                     "Development",
  "apache.org":                    "Development",
  "nodejs.org":                    "Development",
  "deno.land":                     "Development",
  "bun.sh":                        "Development",
  "pnpm.io":                       "Development",
  "yarnpkg.com":                   "Development",
  "lerna.js.org":                  "Development",
  "turborepo.org":                 "Development",
  "nx.dev":                        "Development",
  "astro.build":                   "Development",
  "remix.run":                     "Development",
  "solidjs.com":                   "Development",
  "qwik.builder.io":               "Development",
  "htmx.org":                      "Development",
  "alpinejs.dev":                  "Development",
  "lit.dev":                       "Development",
  "stenciljs.com":                 "Development",
  "emotion.sh":                    "Development",
  "styled-components.com":         "Development",
  "storybook.js.org":              "Development",
  "chromatic.com":                 "Development",
  "playwright.dev":                "Development",
  "cypress.io":                    "Development",
  "jestjs.io":                     "Development",
  "vitest.dev":                    "Development",
  "testing-library.com":           "Development",
  "mochajs.org":                   "Development",
  "chaijs.com":                    "Development",
  "socket.io":                     "Development",
  "expressjs.com":                 "Development",
  "fastify.io":                    "Development",
  "nestjs.com":                    "Development",
  "hono.dev":                      "Development",
  "djangoproject.com":             "Development",
  "flask.palletsprojects.com":     "Development",
  "fastapi.tiangolo.com":          "Development",
  "laravel.com":                   "Development",
  "symfony.com":                   "Development",
  "rubyonrails.org":               "Development",
  "spring.io":                     "Development",
  "quarkus.io":                    "Development",
  "micronaut.io":                  "Development",
  "grpc.io":                       "Development",
  "protobuf.dev":                  "Development",
  "opentelemetry.io":              "Development",
  "jaegertracing.io":              "Development",
  "istio.io":                      "Development",
  "helm.sh":                       "Development",
  "argo-workflows.readthedocs.io": "Development",
  "tekton.dev":                    "Development",
  "github.com/features/actions":   "Development",
  "about.gitlab.com/stages-devops-lifecycle/continuous-integration": "Development",
  "pulumi.com":                    "Development",
  "crossplane.io":                 "Development",
  "neon.tech":                     "Development",
  "turso.tech":                    "Development",
  "cockroachlabs.com":             "Development",
  "fauna.com":                     "Development",
  "appwrite.io":                   "Development",
  "pocketbase.io":                 "Development",
  "convex.dev":                    "Development",
  "xata.io":                       "Development",
  "upstash.com":                   "Development",
  "hookdeck.com":                  "Development",
  "inngest.com":                   "Development",
  "temporal.io":                   "Development",
  "reactivex.io":                  "Development",
  "rxjs.dev":                      "Development",
  "zustand.docs.pmnd.rs":          "Development",
  "redux.js.org":                  "Development",
  "mobx.js.org":                   "Development",
  "tanstack.com":                  "Development",
  "swr.vercel.app":                "Development",
  "trpc.io":                       "Development",
  "zod.dev":                       "Development",
  "valibot.dev":                   "Development",
  "drizzle.team":                  "Development",
  "sequelize.org":                 "Development",
  "typeorm.io":                    "Development",
  "mikro-orm.io":                  "Development",
  "knexjs.org":                    "Development",
  "lucide.dev":                    "Development",
  "radix-ui.com":                  "Development",
  "shadcn.com":                    "Development",
  "ui.aceternity.com":             "Development",
  "daisyui.com":                   "Development",
  "mantine.dev":                   "Development",
  "ant.design":                    "Development",
  "mui.com":                       "Development",
  "chakra-ui.com":                 "Development",
  "headlessui.com":                "Development",
  "floating-ui.com":               "Development",
  "framer.com/motion":             "Development",
  "greensock.com":                 "Development",
  "animejs.com":                   "Development",
  "threejs.org":                   "Development",
  "babylonjs.com":                 "Development",
  "pixijs.com":                    "Development",
  "phaser.io":                     "Development",
  "d3js.org":                      "Development",
  "observable.com":                "Development",
  "vega.github.io":                "Development",
  "echarts.apache.org":            "Development",
  "chartjs.org":                   "Development",
  "recharts.org":                  "Development",
  "nivo.rocks":                    "Development",
  "highcharts.com":                "Development",
  "apexcharts.com":                "Development",
  "mapbox.com":                    "Development",
  "leafletjs.com":                 "Development",
  "openlayers.org":                "Development",
  "cesium.com":                    "Development",
  "deck.gl":                       "Development",
  "turf.io":                       "Development",

  // ══════════════════════════════════════════════════════════════════════════
  // MEDIA & ENTERTAINMENT
  // ══════════════════════════════════════════════════════════════════════════
  "youtube.com":                   "Media & Entertainment",
  "netflix.com":                   "Media & Entertainment",
  "twitch.tv":                     "Media & Entertainment",
  "disneyplus.com":                "Media & Entertainment",
  "hulu.com":                      "Media & Entertainment",
  "max.com":                       "Media & Entertainment",
  "primevideo.com":                "Media & Entertainment",
  "peacocktv.com":                 "Media & Entertainment",
  "paramountplus.com":             "Media & Entertainment",
  "crunchyroll.com":               "Media & Entertainment",
  "funimation.com":                "Media & Entertainment",
  "spotify.com":                   "Media & Entertainment",
  "soundcloud.com":                "Media & Entertainment",
  "tidal.com":                     "Media & Entertainment",
  "deezer.com":                    "Media & Entertainment",
  "bandcamp.com":                  "Media & Entertainment",
  "audiomack.com":                 "Media & Entertainment",
  "pandora.com":                   "Media & Entertainment",
  "music.apple.com":               "Media & Entertainment",
  "music.youtube.com":             "Media & Entertainment",
  "vimeo.com":                     "Media & Entertainment",
  "dailymotion.com":               "Media & Entertainment",
  "rumble.com":                    "Media & Entertainment",
  "odysee.com":                    "Media & Entertainment",
  "bilibili.com":                  "Media & Entertainment",
  "iqiyi.com":                     "Media & Entertainment",
  "youku.com":                     "Media & Entertainment",
  "wetv.vip":                      "Media & Entertainment",
  "mangadex.org":                  "Media & Entertainment",
  "webtoons.com":                  "Media & Entertainment",
  "imdb.com":                      "Media & Entertainment",
  "rottentomatoes.com":            "Media & Entertainment",
  "metacritic.com":                "Media & Entertainment",
  "letterboxd.com":                "Media & Entertainment",
  "goodreads.com":                 "Media & Entertainment",
  "fandom.com":                    "Media & Entertainment",
  "ign.com":                       "Media & Entertainment",
  "gamespot.com":                  "Media & Entertainment",
  "polygon.com":                   "Media & Entertainment",
  "kotaku.com":                    "Media & Entertainment",
  "pcgamer.com":                   "Media & Entertainment",
  "eurogamer.net":                 "Media & Entertainment",
  "steampowered.com":              "Media & Entertainment",
  "epicgames.com":                 "Media & Entertainment",
  "gog.com":                       "Media & Entertainment",
  "itch.io":                       "Media & Entertainment",
  "chess.com":                     "Media & Entertainment",
  "lichess.org":                   "Media & Entertainment",
  "boardgamegeek.com":             "Media & Entertainment",
  "store.steampowered.com":        "Media & Entertainment",
  "xbox.com":                      "Media & Entertainment",
  "playstation.com":               "Media & Entertainment",
  "nintendo.com":                  "Media & Entertainment",
  "gamesradar.com":                "Media & Entertainment",
  "rockstargames.com":             "Media & Entertainment",
  "ea.com":                        "Media & Entertainment",
  "ubisoft.com":                   "Media & Entertainment",
  "blizzard.com":                  "Media & Entertainment",
  "battle.net":                    "Media & Entertainment",
  "riotgames.com":                 "Media & Entertainment",
  "leagueoflegends.com":           "Media & Entertainment",
  "dota2.com":                     "Media & Entertainment",
  "counter-strike.net":            "Media & Entertainment",
  "fortnite.com":                  "Media & Entertainment",
  "minecraft.net":                 "Media & Entertainment",
  "roblox.com":                    "Media & Entertainment",
  "poki.com":                      "Media & Entertainment",
  "coolmathgames.com":             "Media & Entertainment",
  "kongregate.com":                "Media & Entertainment",
  "newgrounds.com":                "Media & Entertainment",
  "armorgames.com":                "Media & Entertainment",
  "crazygames.com":                "Media & Entertainment",
  "y8.com":                        "Media & Entertainment",
  "miniclip.com":                  "Media & Entertainment",
  "nitrome.com":                   "Media & Entertainment",
  "audible.com":                   "Media & Entertainment",
  "scribd.com":                    "Media & Entertainment",
  "kindle.amazon.com":             "Media & Entertainment",
  "libby.app":                     "Media & Entertainment",
  "storygraph.com":                "Media & Entertainment",
  "readcomiconline.li":            "Media & Entertainment",
  "manga-plus.shueisha.com":       "Media & Entertainment",
  "viz.com":                       "Media & Entertainment",
  "radiopaedia.org":               "Media & Entertainment",
  "iheartradio.com":               "Media & Entertainment",
  "tunein.com":                    "Media & Entertainment",
  "last.fm":                       "Media & Entertainment",
  "discogs.com":                   "Media & Entertainment",
  "genius.com":                    "Media & Entertainment",
  "azlyrics.com":                  "Media & Entertainment",
  "lyrics.com":                    "Media & Entertainment",
  "allmusic.com":                  "Media & Entertainment",
  "rateyourmusic.com":             "Media & Entertainment",
  "setlist.fm":                    "Media & Entertainment",
  "songkick.com":                  "Media & Entertainment",
  "ticketmaster.com":              "Media & Entertainment",
  "stubhub.com":                   "Media & Entertainment",
  "seatgeek.com":                  "Media & Entertainment",
  "eventbrite.com":                "Media & Entertainment",
  "livenation.com":                "Media & Entertainment",
  "mubi.com":                      "Media & Entertainment",
  "criterion.com":                 "Media & Entertainment",
  "shudder.com":                   "Media & Entertainment",
  "plex.tv":                       "Media & Entertainment",
  "emby.media":                    "Media & Entertainment",
  "jellyfin.org":                  "Media & Entertainment",
  "kodi.tv":                       "Media & Entertainment",
  "vlcmediaplayer.org":            "Media & Entertainment",
  "nicovideo.jp":                  "Media & Entertainment",
  "abema.tv":                      "Media & Entertainment",
  "viki.com":                      "Media & Entertainment",
  "rakuten.tv":                    "Media & Entertainment",
  "atresseries.com":               "Media & Entertainment",

  // ══════════════════════════════════════════════════════════════════════════
  // SOCIAL
  // ══════════════════════════════════════════════════════════════════════════
  "reddit.com":                    "Social",
  "x.com":                         "Social",
  "twitter.com":                   "Social",
  "linkedin.com":                  "Social",
  "facebook.com":                  "Social",
  "instagram.com":                 "Social",
  "tiktok.com":                    "Social",
  "snapchat.com":                  "Social",
  "pinterest.com":                 "Social",
  "tumblr.com":                    "Social",
  "mastodon.social":               "Social",
  "bsky.app":                      "Social",
  "threads.net":                   "Social",
  "discord.com":                   "Social",
  "slack.com":                     "Social",
  "telegram.org":                  "Social",
  "whatsapp.com":                  "Social",
  "signal.org":                    "Social",
  "messenger.com":                 "Social",
  "line.me":                       "Social",
  "wechat.com":                    "Social",
  "kakaotalk.com":                 "Social",
  "vk.com":                        "Social",
  "ok.ru":                         "Social",
  "weibo.com":                     "Social",
  "quora.com":                     "Social",
  "nextdoor.com":                  "Social",
  "meetup.com":                    "Social",
  "producthunt.com":               "Social",
  "news.ycombinator.com":          "Social",
  "lobste.rs":                     "Social",
  "lemmy.world":                   "Social",
  "lemmy.ml":                      "Social",
  "flipboard.com":                 "Social",
  "mix.com":                       "Social",
  "digg.com":                      "Social",
  "delicious.com":                 "Social",
  "myspace.com":                   "Social",
  "hi5.com":                       "Social",
  "tagged.com":                    "Social",
  "classmates.com":                "Social",
  "care2.com":                     "Social",
  "change.org":                    "Social",
  "medium.com":                    "Social",
  "substack.com":                  "Social",
  "beehiiv.com":                   "Social",
  "ghost.org":                     "Social",
  "wordpress.com":                 "Social",
  "blogger.com":                   "Social",
  "livejournal.com":               "Social",
  "deviantart.com":                "Social",
  "artstation.com":                "Social",
  "behance.net":                   "Social",
  "dribbble.com":                  "Social",
  "500px.com":                     "Social",
  "flickr.com":                    "Social",
  "vsco.com":                      "Social",
  "glass.photo":                   "Social",
  "pixelfed.social":               "Social",
  "gab.com":                       "Social",
  "parler.com":                    "Social",
  "gettr.com":                     "Social",
  "truthsocial.com":               "Social",
  "minds.com":                     "Social",
  "mewe.com":                      "Social",
  "cafemom.com":                   "Social",
  "lunchclub.com":                 "Social",
  "bumble.com":                    "Social",
  "tinder.com":                    "Social",
  "hinge.co":                      "Social",
  "okcupid.com":                   "Social",
  "match.com":                     "Social",
  "eharmony.com":                  "Social",
  "zoosk.com":                     "Social",
  "plentyoffish.com":              "Social",
  "coffee-meets-bagel.com":        "Social",
  "feeld.co":                      "Social",
  "grindr.com":                    "Social",
  "scruff.com":                    "Social",
  "ravelry.com":                   "Social",
  "strava.com/clubs":              "Social",
  "letterboxd.com/members":        "Social",
  "listal.com":                    "Social",
  "myanimelist.net":               "Social",
  "anilist.co":                    "Social",
  "kitsu.io":                      "Social",
  "simkl.com":                     "Social",
  "trakt.tv":                      "Social",
  "tv-time.com":                   "Social",
  "untappd.com":                   "Social",
  "vivino.com":                    "Social",
  "cellartracker.com":             "Social",

  // ══════════════════════════════════════════════════════════════════════════
  // PRODUCTIVITY
  // ══════════════════════════════════════════════════════════════════════════
  "mail.google.com":               "Productivity",
  "calendar.google.com":           "Productivity",
  "docs.google.com":               "Productivity",
  "drive.google.com":              "Productivity",
  "sheets.google.com":             "Productivity",
  "slides.google.com":             "Productivity",
  "forms.google.com":              "Productivity",
  "meet.google.com":               "Productivity",
  "notion.so":                     "Productivity",
  "trello.com":                    "Productivity",
  "asana.com":                     "Productivity",
  "monday.com":                    "Productivity",
  "clickup.com":                   "Productivity",
  "basecamp.com":                  "Productivity",
  "linear.app":                    "Productivity",
  "jira.atlassian.com":            "Productivity",
  "confluence.atlassian.com":      "Productivity",
  "atlassian.com":                 "Productivity",
  "airtable.com":                  "Productivity",
  "coda.io":                       "Productivity",
  "roamresearch.com":              "Productivity",
  "obsidian.md":                   "Productivity",
  "evernote.com":                  "Productivity",
  "onenote.com":                   "Productivity",
  "office.com":                    "Productivity",
  "outlook.com":                   "Productivity",
  "outlook.live.com":              "Productivity",
  "teams.microsoft.com":           "Productivity",
  "sharepoint.com":                "Productivity",
  "dropbox.com":                   "Productivity",
  "box.com":                       "Productivity",
  "icloud.com":                    "Productivity",
  "onedrive.live.com":             "Productivity",
  "zoom.us":                       "Productivity",
  "webex.com":                     "Productivity",
  "whereby.com":                   "Productivity",
  "loom.com":                      "Productivity",
  "calendly.com":                  "Productivity",
  "cal.com":                       "Productivity",
  "doodle.com":                    "Productivity",
  "miro.com":                      "Productivity",
  "figma.com":                     "Productivity",
  "lucidchart.com":                "Productivity",
  "whimsical.com":                 "Productivity",
  "excalidraw.com":                "Productivity",
  "todoist.com":                   "Productivity",
  "ticktick.com":                  "Productivity",
  "any.do":                        "Productivity",
  "craft.do":                      "Productivity",
  "grammarly.com":                 "Productivity",
  "typeform.com":                  "Productivity",
  "surveymonkey.com":              "Productivity",
  "zapier.com":                    "Productivity",
  "make.com":                      "Productivity",
  "ifttt.com":                     "Productivity",
  "n8n.io":                        "Productivity",
  "retool.com":                    "Productivity",
  "bubble.io":                     "Productivity",
  "webflow.com":                   "Productivity",
  "framer.com":                    "Productivity",
  "affinity.serif.com":            "Productivity",
  "hemingwayapp.com":              "Productivity",
  "deepl.com":                     "Productivity",
  "protonmail.com":                "Productivity",
  "fastmail.com":                  "Productivity",
  "hey.com":                       "Productivity",
  "superhuman.com":                "Productivity",
  "spark.readdle.com":             "Productivity",
  "airmail.app":                   "Productivity",
  "thunderbird.net":               "Productivity",
  "zoho.com":                      "Productivity",
  "zoho.com/mail":                 "Productivity",
  "zoho.com/docs":                 "Productivity",
  "smartsheet.com":                "Productivity",
  "wrike.com":                     "Productivity",
  "teamwork.com":                  "Productivity",
  "height.app":                    "Productivity",
  "plane.so":                      "Productivity",
  "shortcut.com":                  "Productivity",
  "pivotaltracker.com":            "Productivity",
  "targetprocess.com":             "Productivity",
  "productboard.com":              "Productivity",
  "roadmunk.com":                  "Productivity",
  "aha.io":                        "Productivity",
  "pendo.io":                      "Productivity",
  "fullstory.com":                 "Productivity",
  "hotjar.com":                    "Productivity",
  "mixpanel.com":                  "Productivity",
  "amplitude.com":                 "Productivity",
  "segment.com":                   "Productivity",
  "heap.io":                       "Productivity",
  "logrocket.com":                 "Productivity",
  "screenpipe.com":                "Productivity",
  "krisp.ai":                      "Productivity",
  "otter.ai":                      "Productivity",
  "fireflies.ai":                  "Productivity",
  "fathom.video":                  "Productivity",
  "read.ai":                       "Productivity",
  "tldv.io":                       "Productivity",
  "grain.com":                     "Productivity",
  "fellow.app":                    "Productivity",
  "hypercontext.com":              "Productivity",
  "dovetail.com":                  "Productivity",
  "mural.co":                      "Productivity",
  "stormboard.com":                "Productivity",
  "conceptboard.com":              "Productivity",
  "klaxoon.com":                   "Productivity",
  "mentimeter.com":                "Productivity",
  "slido.com":                     "Productivity",
  "kahoot.com":                    "Productivity",
  "menti.com":                     "Productivity",
  "padlet.com":                    "Productivity",
  "wakelet.com":                   "Productivity",
  "linktree.com":                  "Productivity",
  "bio.link":                      "Productivity",
  "beacons.ai":                    "Productivity",

  // ══════════════════════════════════════════════════════════════════════════
  // AI & RESEARCH
  // ══════════════════════════════════════════════════════════════════════════
  "chatgpt.com":                   "AI & Research",
  "claude.ai":                     "AI & Research",
  "gemini.google.com":             "AI & Research",
  "copilot.microsoft.com":         "AI & Research",
  "perplexity.ai":                 "AI & Research",
  "you.com":                       "AI & Research",
  "phind.com":                     "AI & Research",
  "poe.com":                       "AI & Research",
  "character.ai":                  "AI & Research",
  "huggingface.co":                "AI & Research",
  "replicate.com":                 "AI & Research",
  "openai.com":                    "AI & Research",
  "anthropic.com":                 "AI & Research",
  "mistral.ai":                    "AI & Research",
  "cohere.com":                    "AI & Research",
  "ai21.com":                      "AI & Research",
  "stability.ai":                  "AI & Research",
  "midjourney.com":                "AI & Research",
  "runwayml.com":                  "AI & Research",
  "elevenlabs.io":                 "AI & Research",
  "suno.com":                      "AI & Research",
  "udio.com":                      "AI & Research",
  "pika.art":                      "AI & Research",
  "together.ai":                   "AI & Research",
  "groq.com":                      "AI & Research",
  "fireworks.ai":                  "AI & Research",
  "anyscale.com":                  "AI & Research",
  "modal.com":                     "AI & Research",
  "wandb.ai":                      "AI & Research",
  "deeplearning.ai":               "AI & Research",
  "fast.ai":                       "AI & Research",
  "arxiv.org":                     "AI & Research",
  "paperswithcode.com":            "AI & Research",
  "semanticscholar.org":           "AI & Research",
  "scholar.google.com":            "AI & Research",
  "researchgate.net":              "AI & Research",
  "academia.edu":                  "AI & Research",
  "jstor.org":                     "AI & Research",
  "pubmed.ncbi.nlm.nih.gov":       "AI & Research",
  "ncbi.nlm.nih.gov":              "AI & Research",
  "sciencedirect.com":             "AI & Research",
  "nature.com":                    "AI & Research",
  "science.org":                   "AI & Research",
  "springer.com":                  "AI & Research",
  "wiley.com":                     "AI & Research",
  "elsevier.com":                  "AI & Research",
  "tandfonline.com":               "AI & Research",
  "sagepub.com":                   "AI & Research",
  "cell.com":                      "AI & Research",
  "plos.org":                      "AI & Research",
  "biorxiv.org":                   "AI & Research",
  "medrxiv.org":                   "AI & Research",
  "ssrn.com":                      "AI & Research",
  "descript.com":                  "AI & Research",
  "lmsys.org":                     "AI & Research",
  "ollama.com":                    "AI & Research",
  "jan.ai":                        "AI & Research",
  "lmstudio.ai":                   "AI & Research",
  "openrouter.ai":                 "AI & Research",
  "civitai.com":                   "AI & Research",
  "leonardo.ai":                   "AI & Research",
  "ideogram.ai":                   "AI & Research",
  "adobe.com/firefly":             "AI & Research",
  "canva.com/ai":                  "AI & Research",
  "jasper.ai":                     "AI & Research",
  "copy.ai":                       "AI & Research",
  "writesonic.com":                "AI & Research",
  "rytr.me":                       "AI & Research",
  "hyperwriteai.com":              "AI & Research",
  "sudowrite.com":                 "AI & Research",
  "novelai.net":                   "AI & Research",
  "inferkit.com":                  "AI & Research",
  "scale.com":                     "AI & Research",
  "labelbox.com":                  "AI & Research",
  "roboflow.com":                  "AI & Research",
  "superannotate.com":             "AI & Research",
  "v7labs.com":                    "AI & Research",
  "activeloop.ai":                 "AI & Research",
  "pinecone.io":                   "AI & Research",
  "weaviate.io":                   "AI & Research",
  "qdrant.tech":                   "AI & Research",
  "chroma.research":               "AI & Research",
  "langchain.com":                 "AI & Research",
  "llamaindex.ai":                 "AI & Research",
  "flowise.ai":                    "AI & Research",
  "dify.ai":                       "AI & Research",
  "botpress.com":                  "AI & Research",
  "rasa.com":                      "AI & Research",
  "landbot.io":                    "AI & Research",
  "voiceflow.com":                 "AI & Research",
  "kore.ai":                       "AI & Research",
  "ibm.com/watson":                "AI & Research",
  "aws.amazon.com/sagemaker":      "AI & Research",
  "azure.microsoft.com/ai":        "AI & Research",
  "cloud.google.com/vertex-ai":    "AI & Research",

  // ══════════════════════════════════════════════════════════════════════════
  // REFERENCE & EDUCATION
  // ══════════════════════════════════════════════════════════════════════════
  "wikipedia.org":                 "Reference",
  "wikimedia.org":                 "Reference",
  "wikidata.org":                  "Reference",
  "wiktionary.org":                "Reference",
  "wikiquote.org":                 "Reference",
  "wikibooks.org":                 "Reference",
  "wikiversity.org":               "Reference",
  "britannica.com":                "Reference",
  "merriam-webster.com":           "Reference",
  "dictionary.com":                "Reference",
  "thesaurus.com":                 "Reference",
  "oxfordlearnersdictionaries.com": "Reference",
  "etymonline.com":                "Reference",
  "wolframalpha.com":              "Reference",
  "mathworld.wolfram.com":         "Reference",
  "khanacademy.org":               "Reference",
  "coursera.org":                  "Reference",
  "edx.org":                       "Reference",
  "udemy.com":                     "Reference",
  "udacity.com":                   "Reference",
  "pluralsight.com":               "Reference",
  "skillshare.com":                "Reference",
  "masterclass.com":               "Reference",
  "brilliant.org":                 "Reference",
  "duolingo.com":                  "Reference",
  "babbel.com":                    "Reference",
  "busuu.com":                     "Reference",
  "rosettastone.com":              "Reference",
  "translate.google.com":          "Reference",
  "archive.org":                   "Reference",
  "gutenberg.org":                 "Reference",
  "openlibrary.org":               "Reference",
  "worldcat.org":                  "Reference",
  "loc.gov":                       "Reference",
  "statista.com":                  "Reference",
  "ourworldindata.org":            "Reference",
  "gapminder.org":                 "Reference",
  "data.worldbank.org":            "Reference",
  "imf.org":                       "Reference",
  "un.org":                        "Reference",
  "who.int":                       "Reference",
  "cdc.gov":                       "Reference",
  "nih.gov":                       "Reference",
  "mayoclinic.org":                "Reference",
  "webmd.com":                     "Reference",
  "healthline.com":                "Reference",
  "medlineplus.gov":               "Reference",
  "coursehero.com":                "Reference",
  "chegg.com":                     "Reference",
  "quizlet.com":                   "Reference",
  "studyblue.com":                 "Reference",
  "sparknotes.com":                "Reference",
  "cliffsnotes.com":               "Reference",
  "gradesaver.com":                "Reference",
  "enotes.com":                    "Reference",
  "litcharts.com":                 "Reference",
  "schmoop.com":                   "Reference",
  "bartleby.com":                  "Reference",
  "iep.utm.edu":                   "Reference",
  "plato.stanford.edu":            "Reference",
  "mathoverflow.net":              "Reference",
  "math.stackexchange.com":        "Reference",
  "physics.stackexchange.com":     "Reference",
  "chemistry.stackexchange.com":   "Reference",
  "biology.stackexchange.com":     "Reference",
  "astronomy.stackexchange.com":   "Reference",
  "geographyrealm.com":            "Reference",
  "nationalgeographic.com":        "Reference",
  "smithsonianmag.com":            "Reference",
  "pbs.org":                       "Reference",
  "discoverychannel.com":          "Reference",
  "history.com":                   "Reference",
  "biography.com":                 "Reference",
  "infoplease.com":                "Reference",
  "encyclopedia.com":              "Reference",
  "worldatlas.com":                "Reference",
  "countrycode.org":               "Reference",
  "numbeo.com":                    "Reference",
  "cia.gov":                       "Reference",
  "census.gov":                    "Reference",
  "bls.gov":                       "Reference",
  "federalreserve.gov":            "Reference",
  "sec.gov":                       "Reference",
  "irs.gov":                       "Reference",
  "usa.gov":                       "Reference",
  "data.gov":                      "Reference",
  "data.europa.eu":                "Reference",
  "eurostat.ec.europa.eu":         "Reference",
  "kaggle.com":                    "Reference",
  "huggingface.co/datasets":       "Reference",
  "zenodo.org":                    "Reference",
  "figshare.com":                  "Reference",
  "dataverse.harvard.edu":         "Reference",
  "opendata.cityofnewyork.us":     "Reference",
  "data.london.gov.uk":            "Reference",
  "data.gov.in":                   "Reference",
  "data.gov.au":                   "Reference",
  "naukri.com":                    "Reference",
  "indeed.com":                    "Reference",
  "glassdoor.com":                 "Reference",
  "monster.com":                   "Reference",
  "ziprecruiter.com":              "Reference",
  "simplyhired.com":               "Reference",
  "dice.com":                      "Reference",
  "levels.fyi":                    "Reference",
  "blind.com":                     "Reference",
  "teamblind.com":                 "Reference",

  // ══════════════════════════════════════════════════════════════════════════
  // NEWS & MEDIA
  // ══════════════════════════════════════════════════════════════════════════
  "cnn.com":                       "News & Media",
  "bbc.com":                       "News & Media",
  "bbc.co.uk":                     "News & Media",
  "nytimes.com":                   "News & Media",
  "theguardian.com":               "News & Media",
  "washingtonpost.com":            "News & Media",
  "wsj.com":                       "News & Media",
  "ft.com":                        "News & Media",
  "reuters.com":                   "News & Media",
  "apnews.com":                    "News & Media",
  "bloomberg.com":                 "News & Media",
  "economist.com":                 "News & Media",
  "theatlantic.com":               "News & Media",
  "newyorker.com":                 "News & Media",
  "time.com":                      "News & Media",
  "forbes.com":                    "News & Media",
  "businessinsider.com":           "News & Media",
  "techcrunch.com":                "News & Media",
  "theverge.com":                  "News & Media",
  "wired.com":                     "News & Media",
  "arstechnica.com":               "News & Media",
  "engadget.com":                  "News & Media",
  "gizmodo.com":                   "News & Media",
  "venturebeat.com":               "News & Media",
  "mashable.com":                  "News & Media",
  "cnet.com":                      "News & Media",
  "zdnet.com":                     "News & Media",
  "pcmag.com":                     "News & Media",
  "tomsguide.com":                 "News & Media",
  "tomshardware.com":              "News & Media",
  "anandtech.com":                 "News & Media",
  "9to5mac.com":                   "News & Media",
  "9to5google.com":                "News & Media",
  "macrumors.com":                 "News & Media",
  "androidauthority.com":          "News & Media",
  "gsmarena.com":                  "News & Media",
  "xda-developers.com":            "News & Media",
  "nbcnews.com":                   "News & Media",
  "abcnews.go.com":                "News & Media",
  "cbsnews.com":                   "News & Media",
  "foxnews.com":                   "News & Media",
  "msnbc.com":                     "News & Media",
  "aljazeera.com":                 "News & Media",
  "dw.com":                        "News & Media",
  "france24.com":                  "News & Media",
  "thehindu.com":                  "News & Media",
  "timesofindia.indiatimes.com":   "News & Media",
  "ndtv.com":                      "News & Media",
  "hindustantimes.com":            "News & Media",
  "scmp.com":                      "News & Media",
  "japantimes.co.jp":              "News & Media",
  "lemonde.fr":                    "News & Media",
  "spiegel.de":                    "News & Media",
  "elpais.com":                    "News & Media",
  "globo.com":                     "News & Media",
  "smh.com.au":                    "News & Media",
  "vox.com":                       "News & Media",
  "vice.com":                      "News & Media",
  "buzzfeed.com":                  "News & Media",
  "huffpost.com":                  "News & Media",
  "politico.com":                  "News & Media",
  "axios.com":                     "News & Media",
  "thehill.com":                   "News & Media",
  "propublica.org":                "News & Media",
  "theintercept.com":              "News & Media",
  "motherjones.com":               "News & Media",
  "thedailybeast.com":             "News & Media",
  "salon.com":                     "News & Media",
  "slate.com":                     "News & Media",
  "reason.com":                    "News & Media",
  "nationalreview.com":            "News & Media",
  "weeklystandard.com":            "News & Media",
  "rollcall.com":                  "News & Media",
  "fivethirtyeight.com":           "News & Media",
  "realclearpolitics.com":         "News & Media",
  "ballotpedia.org":               "News & Media",
  "factcheck.org":                 "News & Media",
  "snopes.com":                    "News & Media",
  "politifact.com":                "News & Media",
  "mediabiasfactcheck.com":        "News & Media",
  "allsides.com":                  "News & Media",
  "technologyreview.com":          "News & Media",
  "scientificamerican.com":        "News & Media",
  "newscientist.com":              "News & Media",
  "popsci.com":                    "News & Media",
  "discovermagazine.com":          "News & Media",
  "quantamagazine.org":            "News & Media",
  "nautil.us":                     "News & Media",
  "aeon.co":                       "News & Media",
  "longreads.com":                 "News & Media",
  "theconversation.com":           "News & Media",
  "psychologytoday.com":           "News & Media",
  "hbr.org":                       "News & Media",
  "mckinsey.com":                  "News & Media",
  "bcg.com":                       "News & Media",
  "deloitte.com":                  "News & Media",
  "pwc.com":                       "News & Media",
  "accenture.com":                 "News & Media",
  "kpmg.com":                      "News & Media",
  "gartner.com":                   "News & Media",
  "forrester.com":                 "News & Media",
  "idc.com":                       "News & Media",
  "infoworld.com":                 "News & Media",
  "computerworld.com":             "News & Media",
  "itpro.co.uk":                   "News & Media",
  "darkreading.com":               "News & Media",
  "securityweek.com":              "News & Media",
  "bleepingcomputer.com":          "News & Media",
  "krebs.security":                "News & Media",
  "krebsonsecurity.com":           "News & Media",
  "threatpost.com":                "News & Media",

  // ══════════════════════════════════════════════════════════════════════════
  // SHOPPING & E-COMMERCE
  // ══════════════════════════════════════════════════════════════════════════
  "amazon.com":                    "Shopping",
  "ebay.com":                      "Shopping",
  "etsy.com":                      "Shopping",
  "walmart.com":                   "Shopping",
  "target.com":                    "Shopping",
  "bestbuy.com":                   "Shopping",
  "costco.com":                    "Shopping",
  "ikea.com":                      "Shopping",
  "wayfair.com":                   "Shopping",
  "homedepot.com":                 "Shopping",
  "lowes.com":                     "Shopping",
  "chewy.com":                     "Shopping",
  "zappos.com":                    "Shopping",
  "nordstrom.com":                 "Shopping",
  "macys.com":                     "Shopping",
  "gap.com":                       "Shopping",
  "oldnavy.com":                   "Shopping",
  "hm.com":                        "Shopping",
  "zara.com":                      "Shopping",
  "uniqlo.com":                    "Shopping",
  "nike.com":                      "Shopping",
  "adidas.com":                    "Shopping",
  "newbalance.com":                "Shopping",
  "underarmour.com":               "Shopping",
  "patagonia.com":                 "Shopping",
  "rei.com":                       "Shopping",
  "newegg.com":                    "Shopping",
  "bhphotovideo.com":              "Shopping",
  "adorama.com":                   "Shopping",
  "aliexpress.com":                "Shopping",
  "alibaba.com":                   "Shopping",
  "taobao.com":                    "Shopping",
  "jd.com":                        "Shopping",
  "pinduoduo.com":                 "Shopping",
  "flipkart.com":                  "Shopping",
  "meesho.com":                    "Shopping",
  "noon.com":                      "Shopping",
  "lazada.com":                    "Shopping",
  "shopee.com":                    "Shopping",
  "temu.com":                      "Shopping",
  "shein.com":                     "Shopping",
  "rakuten.com":                   "Shopping",
  "mercadolibre.com":              "Shopping",
  "poshmark.com":                  "Shopping",
  "depop.com":                     "Shopping",
  "vinted.com":                    "Shopping",
  "grailed.com":                   "Shopping",
  "stockx.com":                    "Shopping",
  "goat.com":                      "Shopping",
  "farfetch.com":                  "Shopping",
  "ssense.com":                    "Shopping",
  "mytheresa.com":                 "Shopping",
  "net-a-porter.com":              "Shopping",
  "matchesfashion.com":            "Shopping",
  "lyst.com":                      "Shopping",
  "shopbop.com":                   "Shopping",
  "revolve.com":                   "Shopping",
  "asos.com":                      "Shopping",
  "boohoo.com":                    "Shopping",
  "prettylittlething.com":         "Shopping",
  "fashionnova.com":               "Shopping",
  "romwe.com":                     "Shopping",
  "wish.com":                      "Shopping",
  "dhgate.com":                    "Shopping",
  "overstock.com":                 "Shopping",
  "groupon.com":                   "Shopping",
  "woot.com":                      "Shopping",
  "slickdeals.net":                "Shopping",
  "dealnews.com":                  "Shopping",
  "bensbargains.com":              "Shopping",
  "camelcamelcamel.com":           "Shopping",
  "honey.com":                     "Shopping",
  "rakuten.com/cash-back":         "Shopping",
  "swagbucks.com":                 "Shopping",
  "ibotta.com":                    "Shopping",
  "checkout51.com":                "Shopping",
  "viggle.com":                    "Shopping",
  "shopstyle.com":                 "Shopping",
  "polyvore.com":                  "Shopping",
  "wheretobuy.co":                 "Shopping",
  "pricespy.co.uk":                "Shopping",
  "idealo.de":                     "Shopping",
  "kelkoo.com":                    "Shopping",
  "shopzilla.com":                 "Shopping",
  "nextag.com":                    "Shopping",
  "pricegrabber.com":              "Shopping",
  "shopmania.com":                 "Shopping",
  "skinstore.com":                 "Shopping",
  "dermstore.com":                 "Shopping",
  "ulta.com":                      "Shopping",
  "sephora.com":                   "Shopping",
  "glossier.com":                  "Shopping",
  "cultbeauty.co.uk":              "Shopping",
  "lookfantastic.com":             "Shopping",
  "feelunique.com":                "Shopping",
  "beautybay.com":                 "Shopping",
  "fragrancenet.com":              "Shopping",
  "jomashop.com":                  "Shopping",
  "watchuseek.com":                "Shopping",
  "hodinkee.com":                  "Shopping",
  "longines.com":                  "Shopping",
  "swatchgroup.com":               "Shopping",
  "cartier.com":                   "Shopping",
  "tiffany.com":                   "Shopping",
  "pandora.net":                   "Shopping",
  "wayfair.ca":                    "Shopping",
  "crate.com":                     "Shopping",
  "potterybarn.com":               "Shopping",
  "westelm.com":                   "Shopping",
  "anthropologie.com":             "Shopping",
  "freepeople.com":                "Shopping",
  "urbanoutfitters.com":           "Shopping",
  "forever21.com":                 "Shopping",
  "express.com":                   "Shopping",
  "bananarepublic.gap.com":        "Shopping",
  "jcrew.com":                     "Shopping",
  "landsend.com":                  "Shopping",
  "llbean.com":                    "Shopping",
  "cabelas.com":                   "Shopping",
  "basspro.com":                   "Shopping",

  // ══════════════════════════════════════════════════════════════════════════
  // FINANCE
  // ══════════════════════════════════════════════════════════════════════════
  "paypal.com":                    "Finance",
  "stripe.com":                    "Finance",
  "square.com":                    "Finance",
  "venmo.com":                     "Finance",
  "cashapp.com":                   "Finance",
  "wise.com":                      "Finance",
  "revolut.com":                   "Finance",
  "n26.com":                       "Finance",
  "robinhood.com":                 "Finance",
  "etrade.com":                    "Finance",
  "fidelity.com":                  "Finance",
  "schwab.com":                    "Finance",
  "vanguard.com":                  "Finance",
  "tdameritrade.com":              "Finance",
  "interactivebrokers.com":        "Finance",
  "webull.com":                    "Finance",
  "tradingview.com":               "Finance",
  "investing.com":                 "Finance",
  "marketwatch.com":               "Finance",
  "finance.yahoo.com":             "Finance",
  "seekingalpha.com":              "Finance",
  "morningstar.com":               "Finance",
  "coinbase.com":                  "Finance",
  "binance.com":                   "Finance",
  "kraken.com":                    "Finance",
  "crypto.com":                    "Finance",
  "coingecko.com":                 "Finance",
  "coinmarketcap.com":             "Finance",
  "blockchain.com":                "Finance",
  "opensea.io":                    "Finance",
  "mint.com":                      "Finance",
  "ynab.com":                      "Finance",
  "nerdwallet.com":                "Finance",
  "bankrate.com":                  "Finance",
  "creditkarma.com":               "Finance",
  "turbotax.intuit.com":           "Finance",
  "quickbooks.intuit.com":         "Finance",
  "freshbooks.com":                "Finance",
  "xero.com":                      "Finance",
  "wave.com":                      "Finance",
  "chime.com":                     "Finance",
  "ally.com":                      "Finance",
  "marcus.com":                    "Finance",
  "discover.com":                  "Finance",
  "capitalone.com":                "Finance",
  "citibank.com":                  "Finance",
  "chase.com":                     "Finance",
  "bankofamerica.com":             "Finance",
  "wellsfargo.com":                "Finance",
  "usbank.com":                    "Finance",
  "pnc.com":                       "Finance",
  "tdbank.com":                    "Finance",
  "regions.com":                   "Finance",
  "suntrust.com":                  "Finance",
  "truist.com":                    "Finance",
  "hsbc.com":                      "Finance",
  "barclays.co.uk":                "Finance",
  "lloydsbank.com":                "Finance",
  "natwest.com":                   "Finance",
  "santander.co.uk":               "Finance",
  "deutschebank.com":              "Finance",
  "bnpparibas.com":                "Finance",
  "societegenerale.com":           "Finance",
  "ing.com":                       "Finance",
  "rabobank.com":                  "Finance",
  "ing.nl":                        "Finance",
  "monzo.com":                     "Finance",
  "starlingbank.com":              "Finance",
  "transferwise.com":              "Finance",
  "payoneer.com":                  "Finance",
  "skrill.com":                    "Finance",
  "neteller.com":                  "Finance",
  "2checkout.com":                 "Finance",
  "braintreepayments.com":         "Finance",
  "adyen.com":                     "Finance",
  "checkout.com":                  "Finance",
  "klarna.com":                    "Finance",
  "afterpay.com":                  "Finance",
  "affirm.com":                    "Finance",
  "sezzle.com":                    "Finance",
  "sofi.com":                      "Finance",
  "lendingclub.com":               "Finance",
  "prosper.com":                   "Finance",
  "betterment.com":                "Finance",
  "wealthfront.com":               "Finance",
  "acorns.com":                    "Finance",
  "stash.com":                     "Finance",
  "m1finance.com":                 "Finance",
  "fundrise.com":                  "Finance",
  "realtyshares.com":              "Finance",
  "masterworks.com":               "Finance",
  "yieldstreet.com":               "Finance",
  "publicfinance.com":             "Finance",
  "public.com":                    "Finance",
  "moomoo.com":                    "Finance",
  "tastytrade.com":                "Finance",
  "thinkorswim.com":               "Finance",
  "questrade.com":                 "Finance",
  "degiro.eu":                     "Finance",
  "trading212.com":                "Finance",
  "freetrade.io":                  "Finance",
  "etoro.com":                     "Finance",
  "ig.com":                        "Finance",
  "cmc-markets.com":               "Finance",
  "forex.com":                     "Finance",
  "oanda.com":                     "Finance",
  "fxcm.com":                      "Finance",
  "naga.com":                      "Finance",
  "plus500.com":                   "Finance",

  // ══════════════════════════════════════════════════════════════════════════
  // TRAVEL & NAVIGATION
  // ══════════════════════════════════════════════════════════════════════════
  "maps.google.com":               "Travel & Navigation",
  "waze.com":                      "Travel & Navigation",
  "openstreetmap.org":             "Travel & Navigation",
  "expedia.com":                   "Travel & Navigation",
  "booking.com":                   "Travel & Navigation",
  "airbnb.com":                    "Travel & Navigation",
  "kayak.com":                     "Travel & Navigation",
  "skyscanner.com":                "Travel & Navigation",
  "tripadvisor.com":               "Travel & Navigation",
  "hotels.com":                    "Travel & Navigation",
  "marriott.com":                  "Travel & Navigation",
  "hilton.com":                    "Travel & Navigation",
  "hyatt.com":                     "Travel & Navigation",
  "ihg.com":                       "Travel & Navigation",
  "southwest.com":                 "Travel & Navigation",
  "delta.com":                     "Travel & Navigation",
  "united.com":                    "Travel & Navigation",
  "aa.com":                        "Travel & Navigation",
  "jetblue.com":                   "Travel & Navigation",
  "ryanair.com":                   "Travel & Navigation",
  "easyjet.com":                   "Travel & Navigation",
  "ba.com":                        "Travel & Navigation",
  "lufthansa.com":                 "Travel & Navigation",
  "emirates.com":                  "Travel & Navigation",
  "uber.com":                      "Travel & Navigation",
  "lyft.com":                      "Travel & Navigation",
  "grab.com":                      "Travel & Navigation",
  "flightradar24.com":             "Travel & Navigation",
  "alltrails.com":                 "Travel & Navigation",
  "komoot.com":                    "Travel & Navigation",
  "hostelworld.com":               "Travel & Navigation",
  "viator.com":                    "Travel & Navigation",
  "vrbo.com":                      "Travel & Navigation",
  "homeaway.com":                  "Travel & Navigation",
  "vacasa.com":                    "Travel & Navigation",
  "hotwire.com":                   "Travel & Navigation",
  "priceline.com":                 "Travel & Navigation",
  "lastminute.com":                "Travel & Navigation",
  "momondo.com":                   "Travel & Navigation",
  "cheapflights.com":              "Travel & Navigation",
  "travelocity.com":               "Travel & Navigation",
  "orbitz.com":                    "Travel & Navigation",
  "makemytrip.com":                "Travel & Navigation",
  "cleartrip.com":                 "Travel & Navigation",
  "yatra.com":                     "Travel & Navigation",
  "ixigo.com":                     "Travel & Navigation",
  "redbus.in":                     "Travel & Navigation",
  "goibibo.com":                   "Travel & Navigation",
  "agoda.com":                     "Travel & Navigation",
  "traveloka.com":                 "Travel & Navigation",
  "klook.com":                     "Travel & Navigation",
  "airasia.com":                   "Travel & Navigation",
  "singaporeair.com":              "Travel & Navigation",
  "cathaypacific.com":             "Travel & Navigation",
  "qantas.com":                    "Travel & Navigation",
  "airnewzealand.com":             "Travel & Navigation",
  "britishairways.com":            "Travel & Navigation",
  "klm.com":                       "Travel & Navigation",
  "airfrance.com":                 "Travel & Navigation",
  "iberia.com":                    "Travel & Navigation",
  "turkishairlines.com":           "Travel & Navigation",
  "aeroflot.ru":                   "Travel & Navigation",
  "etihad.com":                    "Travel & Navigation",
  "qatarairways.com":              "Travel & Navigation",
  "saudiaairlines.com":            "Travel & Navigation",
  "flydubai.com":                  "Travel & Navigation",
  "indigo.in":                     "Travel & Navigation",
  "spicejet.com":                  "Travel & Navigation",
  "vistara.com":                   "Travel & Navigation",
  "seat61.com":                    "Travel & Navigation",
  "amtrak.com":                    "Travel & Navigation",
  "eurostar.com":                  "Travel & Navigation",
  "bahn.de":                       "Travel & Navigation",
  "sncf.com":                      "Travel & Navigation",
  "trenitalia.com":                "Travel & Navigation",
  "renfe.com":                     "Travel & Navigation",
  "raileurope.com":                "Travel & Navigation",
  "busbud.com":                    "Travel & Navigation",
  "flixbus.com":                   "Travel & Navigation",
  "greyhound.com":                 "Travel & Navigation",
  "megabus.com":                   "Travel & Navigation",
  "rome2rio.com":                  "Travel & Navigation",
  "roadtrippers.com":              "Travel & Navigation",
  "parkwhiz.com":                  "Travel & Navigation",
  "spothero.com":                  "Travel & Navigation",
  "parkopedia.com":                "Travel & Navigation",
  "gasBuddy.com":                  "Travel & Navigation",
  "plugshare.com":                 "Travel & Navigation",
  "chargepoint.com":               "Travel & Navigation",
  "turo.com":                      "Travel & Navigation",
  "zipcar.com":                    "Travel & Navigation",
  "hertz.com":                     "Travel & Navigation",
  "enterprise.com":                "Travel & Navigation",
  "avis.com":                      "Travel & Navigation",
  "budget.com":                    "Travel & Navigation",
  "sixt.com":                      "Travel & Navigation",
  "rentalcars.com":                "Travel & Navigation",
  "wikitravel.org":                "Travel & Navigation",
  "lonelyplanet.com":              "Travel & Navigation",
  "frommers.com":                  "Travel & Navigation",
  "roughguides.com":               "Travel & Navigation",
  "smartertravel.com":             "Travel & Navigation",
  "travelandleisure.com":          "Travel & Navigation",
  "cntraveler.com":                "Travel & Navigation",
  "traveler.nationalgeographic.com": "Travel & Navigation",

  // ══════════════════════════════════════════════════════════════════════════
  // FOOD & DELIVERY
  // ══════════════════════════════════════════════════════════════════════════
  "doordash.com":                  "Food & Delivery",
  "ubereats.com":                  "Food & Delivery",
  "grubhub.com":                   "Food & Delivery",
  "instacart.com":                 "Food & Delivery",
  "seamless.com":                  "Food & Delivery",
  "deliveroo.co.uk":               "Food & Delivery",
  "justeat.com":                   "Food & Delivery",
  "zomato.com":                    "Food & Delivery",
  "swiggy.com":                    "Food & Delivery",
  "yelp.com":                      "Food & Delivery",
  "opentable.com":                 "Food & Delivery",
  "resy.com":                      "Food & Delivery",
  "eater.com":                     "Food & Delivery",
  "allrecipes.com":                "Food & Delivery",
  "epicurious.com":                "Food & Delivery",
  "food52.com":                    "Food & Delivery",
  "seriouseats.com":               "Food & Delivery",
  "bonappetit.com":                "Food & Delivery",
  "yummly.com":                    "Food & Delivery",
  "tasty.co":                      "Food & Delivery",
  "hellofresh.com":                "Food & Delivery",
  "blueapron.com":                 "Food & Delivery",
  "sunbasket.com":                 "Food & Delivery",
  "marleyspoon.com":               "Food & Delivery",
  "everyplate.com":                "Food & Delivery",
  "homechef.com":                  "Food & Delivery",
  "gobble.com":                    "Food & Delivery",
  "freshly.com":                   "Food & Delivery",
  "factor75.com":                  "Food & Delivery",
  "trifecta.com":                  "Food & Delivery",
  "green-chef.com":                "Food & Delivery",
  "hungry.com":                    "Food & Delivery",
  "goldbelly.com":                 "Food & Delivery",
  "caviar.com":                    "Food & Delivery",
  "postmates.com":                 "Food & Delivery",
  "pizzahut.com":                  "Food & Delivery",
  "dominos.com":                   "Food & Delivery",
  "papajohns.com":                 "Food & Delivery",
  "mcdonalds.com":                 "Food & Delivery",
  "bk.com":                        "Food & Delivery",
  "tacobell.com":                  "Food & Delivery",
  "wendys.com":                    "Food & Delivery",
  "chick-fil-a.com":               "Food & Delivery",
  "chipotle.com":                  "Food & Delivery",
  "subway.com":                    "Food & Delivery",
  "starbucks.com":                 "Food & Delivery",
  "dunkindonuts.com":              "Food & Delivery",
  "recipes.simplyrecipes.com":     "Food & Delivery",
  "cookingclassy.com":             "Food & Delivery",
  "minimalistbaker.com":           "Food & Delivery",
  "skinnytaste.com":               "Food & Delivery",
  "pinchofyum.com":                "Food & Delivery",
  "budgetbytes.com":               "Food & Delivery",
  "thekitchn.com":                 "Food & Delivery",
  "smittenkitchen.com":            "Food & Delivery",
  "davidlebovitz.com":             "Food & Delivery",
  "101cookbooks.com":              "Food & Delivery",
  "justonecookbook.com":           "Food & Delivery",
  "maangchi.com":                  "Food & Delivery",
  "serious-eats.com":              "Food & Delivery",
  "dinnerthendessert.com":         "Food & Delivery",
  "thepioneerwoman.com":           "Food & Delivery",
  "foodnetwork.com":               "Food & Delivery",
  "cookingchannel.com":            "Food & Delivery",
  "chowhound.com":                 "Food & Delivery",
  "egullet.org":                   "Food & Delivery",

  // ══════════════════════════════════════════════════════════════════════════
  // SEARCH & UTILITIES
  // ══════════════════════════════════════════════════════════════════════════
  "google.com":                    "Search & Utilities",
  "bing.com":                      "Search & Utilities",
  "duckduckgo.com":                "Search & Utilities",
  "yahoo.com":                     "Search & Utilities",
  "baidu.com":                     "Search & Utilities",
  "yandex.com":                    "Search & Utilities",
  "ecosia.org":                    "Search & Utilities",
  "kagi.com":                      "Search & Utilities",
  "startpage.com":                 "Search & Utilities",
  "ask.com":                       "Search & Utilities",
  "aol.com":                       "Search & Utilities",
  "haveibeenpwned.com":            "Search & Utilities",
  "virustotal.com":                "Search & Utilities",
  "web.archive.org":               "Search & Utilities",
  "bit.ly":                        "Search & Utilities",
  "tinyurl.com":                   "Search & Utilities",
  "pastebin.com":                  "Search & Utilities",
  "ipinfo.io":                     "Search & Utilities",
  "whatismyip.com":                "Search & Utilities",
  "downdetector.com":              "Search & Utilities",
  "speedtest.net":                 "Search & Utilities",
  "fast.com":                      "Search & Utilities",
  "wetransfer.com":                "Search & Utilities",
  "imgur.com":                     "Search & Utilities",
  "unsplash.com":                  "Search & Utilities",
  "pexels.com":                    "Search & Utilities",
  "pixabay.com":                   "Search & Utilities",
  "freepik.com":                   "Search & Utilities",
  "flaticon.com":                  "Search & Utilities",
  "fonts.google.com":              "Search & Utilities",
  "fontawesome.com":               "Search & Utilities",
  "canva.com":                     "Search & Utilities",
  "adobe.com":                     "Search & Utilities",
  "photopea.com":                  "Search & Utilities",
  "remove.bg":                     "Search & Utilities",
  "squoosh.app":                   "Search & Utilities",
  "tinypng.com":                   "Search & Utilities",
  "convertio.co":                  "Search & Utilities",
  "smallpdf.com":                  "Search & Utilities",
  "ilovepdf.com":                  "Search & Utilities",
  "calculator.net":                "Search & Utilities",
  "timeanddate.com":               "Search & Utilities",
  "xe.com":                        "Search & Utilities",
  "weather.com":                   "Search & Utilities",
  "wunderground.com":              "Search & Utilities",
  "accuweather.com":               "Search & Utilities",
  "weather.gov":                   "Search & Utilities",
  "windy.com":                     "Search & Utilities",
  "ventusky.com":                  "Search & Utilities",
  "nullschool.net":                "Search & Utilities",
  "earth.nullschool.net":          "Search & Utilities",
  "wolfram.com":                   "Search & Utilities",
  "symbolab.com":                  "Search & Utilities",
  "desmos.com":                    "Search & Utilities",
  "geogebra.org":                  "Search & Utilities",
  "mathway.com":                   "Search & Utilities",
  "photomath.com":                 "Search & Utilities",
  "units-converter.com":           "Search & Utilities",
  "unitconverters.net":            "Search & Utilities",
  "metric-conversions.org":        "Search & Utilities",
  "random.org":                    "Search & Utilities",
  "randomwordgenerator.com":       "Search & Utilities",
  "fakepersongenerator.com":       "Search & Utilities",
  "lipsum.com":                    "Search & Utilities",
  "loremipsum.io":                 "Search & Utilities",
  "htmlcolorcodes.com":            "Search & Utilities",
  "colorhunt.co":                  "Search & Utilities",
  "coolors.co":                    "Search & Utilities",
  "paletton.com":                  "Search & Utilities",
  "colorzilla.com":                "Search & Utilities",
  "regexr.com":                    "Search & Utilities",
  "regex101.com":                  "Search & Utilities",
  "crontab.guru":                  "Search & Utilities",
  "jsonlint.com":                  "Search & Utilities",
  "jsonformatter.org":             "Search & Utilities",
  "base64decode.org":              "Search & Utilities",
  "urlencoder.org":                "Search & Utilities",
  "jwt.io":                        "Search & Utilities",
  "curl.se":                       "Search & Utilities",
  "httpbin.org":                   "Search & Utilities",
  "requestbin.com":                "Search & Utilities",
  "webhook.site":                  "Search & Utilities",
  "mocky.io":                      "Search & Utilities",
  "jsonplaceholder.typicode.com":  "Search & Utilities",
  "fakejson.com":                  "Search & Utilities",
  "whois.domaintools.com":         "Search & Utilities",
  "networksolutions.com":          "Search & Utilities",
  "godaddy.com":                   "Search & Utilities",
  "namecheap.com":                 "Search & Utilities",
  "name.com":                      "Search & Utilities",
  "porkbun.com":                   "Search & Utilities",
  "dynadot.com":                   "Search & Utilities",
  "hover.com":                     "Search & Utilities",
  "iwantmyname.com":               "Search & Utilities",
  "domains.google.com":            "Search & Utilities",
  "squarespace.com/domains":       "Search & Utilities",
  "cloudflare.com/registrar":      "Search & Utilities",
  "1password.com":                 "Search & Utilities",
  "lastpass.com":                  "Search & Utilities",
  "bitwarden.com":                 "Search & Utilities",
  "dashlane.com":                  "Search & Utilities",
  "keepass.info":                  "Search & Utilities",
  "nordpass.com":                  "Search & Utilities",
  "protonvpn.com":                 "Search & Utilities",
  "nordvpn.com":                   "Search & Utilities",
  "expressvpn.com":                "Search & Utilities",
  "surfshark.com":                 "Search & Utilities",
  "mullvad.net":                   "Search & Utilities",
  "privateinternetaccess.com":     "Search & Utilities",
  "torproject.org":                "Search & Utilities",

  // ══════════════════════════════════════════════════════════════════════════
  // HEALTH & FITNESS
  // ══════════════════════════════════════════════════════════════════════════
  "strava.com":                    "Health & Fitness",
  "garmin.com":                    "Health & Fitness",
  "fitbit.com":                    "Health & Fitness",
  "myfitnesspal.com":              "Health & Fitness",
  "loseit.com":                    "Health & Fitness",
  "noom.com":                      "Health & Fitness",
  "calm.com":                      "Health & Fitness",
  "headspace.com":                 "Health & Fitness",
  "peloton.com":                   "Health & Fitness",
  "classpass.com":                 "Health & Fitness",
  "zwift.com":                     "Health & Fitness",
  "trainingpeaks.com":             "Health & Fitness",
  "runkeeper.com":                 "Health & Fitness",
  "mapmyrun.com":                  "Health & Fitness",
  "betterhelp.com":                "Health & Fitness",
  "talkspace.com":                 "Health & Fitness",
  "zocdoc.com":                    "Health & Fitness",
  "goodrx.com":                    "Health & Fitness",
  "drugs.com":                     "Health & Fitness",
  "runtastic.com":                 "Health & Fitness",
  "sleepfoundation.org":           "Health & Fitness",
  "nike.com/nrc":                  "Health & Fitness",
  "apple.com/apple-fitness-plus":  "Health & Fitness",
  "whoop.com":                     "Health & Fitness",
  "ouraring.com":                  "Health & Fitness",
  "8fit.com":                      "Health & Fitness",
  "stronglifts.com":               "Health & Fitness",
  "bodybuilding.com":              "Health & Fitness",
  "muscleandfitness.com":          "Health & Fitness",
  "menshealth.com":                "Health & Fitness",
  "womenshealthmag.com":           "Health & Fitness",
  "shape.com":                     "Health & Fitness",
  "self.com":                      "Health & Fitness",
  "runnersworld.com":              "Health & Fitness",
  "cyclingnews.com":               "Health & Fitness",
  "triathlete.com":                "Health & Fitness",
  "swimmingworld.com":             "Health & Fitness",
  "crossfit.com":                  "Health & Fitness",
  "spartan.com":                   "Health & Fitness",
  "openfit.com":                   "Health & Fitness",
  "dailyburn.com":                 "Health & Fitness",
  "grokker.com":                   "Health & Fitness",
  "ymca.net":                      "Health & Fitness",
  "planetfitness.com":             "Health & Fitness",
  "equinox.com":                   "Health & Fitness",
  "orangetheory.com":              "Health & Fitness",
  "soulcycle.com":                 "Health & Fitness",
  "crunch.com":                    "Health & Fitness",
  "anytimefitness.com":            "Health & Fitness",
  "24hourfitness.com":             "Health & Fitness",
  "lesmills.com":                  "Health & Fitness",
  "mindbodyonline.com":            "Health & Fitness",
  "healow.com":                    "Health & Fitness",
  "myChart.org":                   "Health & Fitness",
  "epic.com":                      "Health & Fitness",
  "teladoc.com":                   "Health & Fitness",
  "mdlive.com":                    "Health & Fitness",
  "hinge.health":                  "Health & Fitness",
  "noom.com/programs":             "Health & Fitness",
  "weightwatchers.com":            "Health & Fitness",
  "optavia.com":                   "Health & Fitness",
  "nutrisystem.com":               "Health & Fitness",
  "jennycraig.com":                "Health & Fitness",
  "isagenix.com":                  "Health & Fitness",
  "beachbody.com":                 "Health & Fitness",
  "insanityworkout.com":           "Health & Fitness",
  "p90x.beachbody.com":            "Health & Fitness",
  "precision-nutrition.com":       "Health & Fitness",
  "examine.com":                   "Health & Fitness",
  "labdoor.com":                   "Health & Fitness",
  "iherb.com":                     "Health & Fitness",
  "vitacost.com":                  "Health & Fitness",
  "swansonvitamins.com":           "Health & Fitness",
  "gnc.com":                       "Health & Fitness",
  "vitaminshoppe.com":             "Health & Fitness",
};

/**
 * Maps a domain name to a pre-defined browsing category string or returns a fallback category based on public suffix heuristics.
 * @param {string} domain - The target hostname to classify.
 * @returns {string} The resolved category label (e.g. "Development", "Reference", or "General").
 */
function getCategory(domain) {
  if (CATEGORY_MAP[domain]) return CATEGORY_MAP[domain];
  if (domain.endsWith(".edu")) return "Education";
  if (domain.endsWith(".gov")) return "Government";
  if (domain.endsWith(".org")) return "Reference";
  return "General";
}

/**
 * Formats raw domain metadata records into flat category node objects for Chart.js treemap rendering.
 * @param {Object<string, {totalVisits:number}>} rawData - Domain data dictionary keying hostnames to total visit counts.
 * @returns {Array<{category:string, name:string, value:number}>} Array of structured treemap data points, excluding sites visited less than twice.
 */
export function processTreemapData(rawData) {
  console.log("[DeepSurf:AnalyticsProcessor] Processing treemap data...");
  const treeData = [];
  
  for (const [domain, data] of Object.entries(rawData)) {

    // We exclude domains with fewer than 2 visits to clean up chart layouts by filtering out single-click search results or temporary redirections.
    if (data.totalVisits < 2) continue;

    treeData.push({
      category: getCategory(domain),
      name: domain,
      value: data.totalVisits
    });
  }

  return treeData;
}

/**
 * Transforms raw hourly browse counts into a coordinate list matching weekday indices and hour cells for heatmap plots.
 * @param {Object<string, {hourlyDistribution:Object<string, number>}>} rawData - Domain records containing hourly visit distributions keyed by "Day_Hour".
 * @returns {Array<{x:number, y:string, v:number}>} Array of 168 coordinate objects mapping hours (x) and day labels (y) to cumulative visit counts (v).
 */
export function processHeatmapData(rawData) {
  console.log("[DeepSurf:AnalyticsProcessor] Processing heatmap data...");
  const DAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
  const grid = [];

  // We initialize the entire grid to zero counts to ensure Chart.js renders a complete 168-cell matrix even if no activity occurred during specific hours.
  for (let d = 0; d < 7; d++) {
    for (let h = 0; h < 24; h++) {
      grid.push({ x: h, y: DAYS[d], v: 0 });
    }
  }

  for (const data of Object.values(rawData)) {
    if (!data.hourlyDistribution) continue;

    for (const [key, count] of Object.entries(data.hourlyDistribution)) {
      const [dayStr, hourStr] = key.split("_");
      const hour = parseInt(hourStr, 10);
      
      const cell = grid.find(c => c.y === dayStr && c.x === hour);
      if (cell) {
        cell.v += count;
      }
    }
  }

  return grid;
}

/**
 * Extracts daily counts of newly discovered domains within a rolling time window.
 * @param {Object<string, {firstVisited:number}>} rawData - Domain records keying hostnames to their initial visit timestamps.
 * @param {number} [daysBack=14] - The trailing timeline window span in calendar days.
 * @returns {{labels:string[], discoveries:number[]}} Chart labels array matching calendar days, and the corresponding array of discovery frequencies.
 */
export function processDiscoveryData(rawData, daysBack = 14) {
  console.log(`[DeepSurf:AnalyticsProcessor] Processing discovery data for last ${daysBack} days...`);
  const labels = [];
  const discoveries = [];

  const endOfToday = new Date();
  endOfToday.setHours(23, 59, 59, 999);
  
  for (let i = daysBack - 1; i >= 0; i--) {

    // We subtract day offsets in milliseconds from the end of today to construct accurate sequential calendar boundaries for the timeline chart.
    const targetDate = new Date(endOfToday.getTime() - (i * 24 * 60 * 60 * 1000));

    labels.push(`${targetDate.getMonth() + 1}/${targetDate.getDate()}`);
    
    const startOfDay = targetDate.getTime() - (24 * 60 * 60 * 1000);
    const endOfDay = targetDate.getTime();

    const newDomainsThatDay = Object.values(rawData).filter(d => 
      d.firstVisited > startOfDay && d.firstVisited <= endOfDay
    ).length;
    
    discoveries.push(newDomainsThatDay);
  }

  return { labels, discoveries };
}